#include <stdio.h>
#include <stdbool.h>
#include "mmio.h"

#define CONTROL_ADDRESS 0x90020000

#define OFFSET_CONTROL_ADDRESS(addr) (CONTROL_ADDRESS + addr)

#define FETCH_ENABLE OFFSET_CONTROL_ADDRESS(0x00)
#define FETCH_OP_OPCODE OFFSET_CONTROL_ADDRESS(0x04)
#define FETCH_OP_TOKEN_CHANNEL OFFSET_CONTROL_ADDRESS(0x08)
#define FETCH_OP_VALID OFFSET_CONTROL_ADDRESS(0x0C)
#define FETCH_RUNCFG_VALID OFFSET_CONTROL_ADDRESS(0x0E)
#define FETCH_RUNCFG_DRAM_BASE OFFSET_CONTROL_ADDRESS(0x10)
#define FETCH_RUNCFG_DRAM_BLOCK_SIZE OFFSET_CONTROL_ADDRESS(0x18)
#define FETCH_RUNCFG_DRAM_BLOCK_OFFSET OFFSET_CONTROL_ADDRESS(0x1C)
#define FETCH_RUNCFG_DRAM_BLOCK_COUNT OFFSET_CONTROL_ADDRESS(0x20)
#define FETCH_RUNCFG_TILES_PER_ROW OFFSET_CONTROL_ADDRESS(0x28)
#define FETCH_RUNCFG_BRAM_ADDR_BASE OFFSET_CONTROL_ADDRESS(0x30)
#define FETCH_RUNCFG_BRAM_ID_START OFFSET_CONTROL_ADDRESS(0x38)
#define FETCH_RUNCFG_BRAM_ID_RANGE OFFSET_CONTROL_ADDRESS(0x40)
#define FETCH_OP_COUNT OFFSET_CONTROL_ADDRESS(0x48)

// Execute stage variables
#define EXEC_ENABLE OFFSET_CONTROL_ADDRESS(0x4C)
#define EXEC_OP_VALID OFFSET_CONTROL_ADDRESS(0x50)
#define EXEC_OP_OPCODE OFFSET_CONTROL_ADDRESS(0x54)
#define EXEC_OP_TOKEN_CHANNEL OFFSET_CONTROL_ADDRESS(0x58)
#define EXEC_RUNCFG_VALID OFFSET_CONTROL_ADDRESS(0x5C)
#define EXEC_RUNCFG_CLEAR_BEFORE_FIRST_ACCUMULATION OFFSET_CONTROL_ADDRESS(0x60)
#define EXEC_RUNCFG_RHS_OFFSET OFFSET_CONTROL_ADDRESS(0x68)
#define EXEC_RUNCFG_LHS_OFFSET OFFSET_CONTROL_ADDRESS(0x70)
#define EXEC_RUNCFG_NEGATE OFFSET_CONTROL_ADDRESS(0x78)
#define EXEC_RUNCFG_NUM_TILES OFFSET_CONTROL_ADDRESS(0x7C)
#define EXEC_RUNCFG_WRITE_EN OFFSET_CONTROL_ADDRESS(0x84)
#define EXEC_RUNCFG_WRITE_ADDR OFFSET_CONTROL_ADDRESS(0x88)
#define EXEC_RUNCFG_SHIFT_AMOUNT OFFSET_CONTROL_ADDRESS(0x8C)
#define EXEC_RUNCFG_OP_COUNT OFFSET_CONTROL_ADDRESS(0x90)

// Result stage variables
#define RESULT_ENABLE OFFSET_CONTROL_ADDRESS(0x98)
#define RESULT_OP_VALID OFFSET_CONTROL_ADDRESS(0x9A)
#define RESULT_OP_OPCODE OFFSET_CONTROL_ADDRESS(0x9C)
#define RESULT_OP_TOKEN_CHANNEL OFFSET_CONTROL_ADDRESS(0x9E)
#define RESULT_RUNCFG_VALID OFFSET_CONTROL_ADDRESS(0xA0)
#define RESULT_RUNCFG_DRAM_BASE OFFSET_CONTROL_ADDRESS(0xA8)
#define RESULT_RUNCFG_DRAM_SKIP OFFSET_CONTROL_ADDRESS(0xB0)
#define RESULT_RUNCFG_RESMEM_ADDR OFFSET_CONTROL_ADDRESS(0xB8)
#define RESULT_RUNCFG_WAIT_COMPLETE OFFSET_CONTROL_ADDRESS(0xBA)
#define RESULT_RUNCFG_WAIT_COMPLETE_BYTES OFFSET_CONTROL_ADDRESS(0xC4)
#define RESULT_OP_COUNT OFFSET_CONTROL_ADDRESS(0xCA)

// Hardware config for reading
#define READ_CHAN_WIDTH OFFSET_CONTROL_ADDRESS(0xD4)
#define WRITE_CHAN_WIDTH OFFSET_CONTROL_ADDRESS(0xDA)
#define DPA_DIM_LHS OFFSET_CONTROL_ADDRESS(0xE4)
#define DPA_DIM_RHS OFFSET_CONTROL_ADDRESS(0xEA)
#define DPA_DIM_COMMON OFFSET_CONTROL_ADDRESS(0xF4)
#define LHS_ENTRIES_PER_MEM OFFSET_CONTROL_ADDRESS(0xFA)
#define RHS_ENTRIES_PER_MEM OFFSET_CONTROL_ADDRESS(0x104)
#define ACC_WIDTH OFFSET_CONTROL_ADDRESS(0x10A)
#define MAX_SHIFT_STEPS OFFSET_CONTROL_ADDRESS(0x114)
#define CMD_QUEUE_ENTRIES OFFSET_CONTROL_ADDRESS(0x11A)

// Values are ready
#define FETCH_RUNCFG_READY OFFSET_CONTROL_ADDRESS(0x124)
#define EXEC_RUNCFG_READY OFFSET_CONTROL_ADDRESS(0x128)
#define RESULT_RUNCFG_READY OFFSET_CONTROL_ADDRESS(0x13c)

#define FETCH_OP_READY OFFSET_CONTROL_ADDRESS(0x140)
#define EXEC_OP_READY OFFSET_CONTROL_ADDRESS(0x144)
#define RESULT_OP_READY OFFSET_CONTROL_ADDRESS(0x148)