#define FETCH_ENABLE 0x00
#define FETCH_OP_OPCODE 0x04
#define FETCH_OP_TOKEN_CHANNEL 0x08
#define FETCH_OP_VALID 0x0C
#define FETCH_RUNCFG_VALID 0x0E
#define FETCH_RUNCFG_DRAM_BASE 0x10
#define FETCH_RUNCFG_DRAM_BLOCK_SIZE 0x18
#define FETCH_RUNCFG_DRAM_BLOCK_OFFSET 0x1C
#define FETCH_RUNCFG_DRAM_BLOCK_COUNT 0x20
#define FETCH_RUNCFG_TILES_PER_ROW 0x28
#define FETCH_RUNCFG_BRAM_ADDR_BASE 0x30
#define FETCH_RUNCFG_BRAM_ID_START 0x38
#define FETCH_RUNCFG_BRAM_ID_RANGE 0x40
#define FETCH_OP_COUNT 0x48

// Execute stage variables
#define EXEC_ENABLE 0x4C
#define EXEC_OP_VALID 0x50
#define EXEC_OP_OPCODE 0x54
#define EXEC_OP_TOKEN_CHANNEL 0x58
#define EXEC_RUNCFG_VALID 0x5C
#define EXEC_RUNCFG_CLEAR_BEFORE_FIRST_ACCUMULATION 0x60
#define EXEC_RUNCFG_RHS_OFFSET 0x68
#define EXEC_RUNCFG_LHS_OFFSET 0x70
#define EXEC_RUNCFG_NEGATE 0x78
#define EXEC_RUNCFG_NUM_TILES 0x7C
#define EXEC_RUNCFG_WRITE_EN 0x84
#define EXEC_RUNCFG_WRITE_ADDR 0x88
#define EXEC_RUNCFG_SHIFT_AMOUNT 0x8C
#define EXEC_OP_COUNT 0x90

// Result stage variables
#define RESULT_ENABLE 0x98
#define RESULT_OP_VALID 0x9A
#define RESULT_OP_OPCODE 0x9C
#define RESULT_OP_TOKEN_CHANNEL 0x9E
#define RESULT_RUNCFG_VALID 0xA0
#define RESULT_RUNCFG_DRAM_BASE 0xA8
#define RESULT_RUNCFG_DRAM_SKIP 0xB0
#define RESULT_RUNCFG_RESMEM_ADDR 0xB8
#define RESULT_RUNCFG_WAIT_COMPLETE 0xC0
#define RESULT_RUNCFG_WAIT_COMPLETE_BYTES 0xC8
#define RESULT_OP_COUNT 0xD0

// Hardware config for reading
#define READ_CHAN_WIDTH 0xD8
#define WRITE_CHAN_WIDTH 0xE0
#define DPA_DIM_LHS 0xE8
#define DPA_DIM_RHS 0xF0
#define DPA_DIM_COMMON 0xF8
#define LHS_ENTRIES_PER_MEM 0x100
#define RHS_ENTRIES_PER_MEM 0x108
#define ACC_WIDTH 0x110
#define MAX_SHIFT_STEPS 0x118
#define CMD_QUEUE_ENTRIES 0x120

// Values are ready
#define FETCH_RUNCFG_READY 0x128
#define EXEC_RUNCFG_READY 0x130
#define RESULT_RUNCFG_READY 0x134

#define FETCH_OP_READY 0x138
#define EXEC_OP_READY 0x13C
#define RESULT_OP_READY 0x140

// CC
#define PERF_CC 0x144
#define CC_ENABLE 0x14C

// Perf fetch
#define PERF_FETCH_COUNT 0x150
#define PERF_FETCH_SEL 0x158

// Perf exec
#define PERF_EXEC_COUNT 0x15C
#define PERF_EXEC_SEL 0x164

// Perf result
#define PERF_RES_COUNT 0x168
#define PERF_RES_SEL 0x170

#define RESET 0x174
#define SIGNATURE 0x178

